// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU4uWcbx6WKGaxn8q630j6cyIN8QA0pd8',
    appId: '1:631469996703:web:e35cd8717a492305fb00aa',
    messagingSenderId: '631469996703',
    projectId: 'test-fluternotify',
    authDomain: 'test-fluternotify.firebaseapp.com',
    storageBucket: 'test-fluternotify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3iC-eKZDO71YQhSmf4ZXYTrLeta4bmRw',
    appId: '1:631469996703:android:5631bb200116390dfb00aa',
    messagingSenderId: '631469996703',
    projectId: 'test-fluternotify',
    storageBucket: 'test-fluternotify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq-rkqEUoF-H9APgpqbfhoZoi5EpcydIk',
    appId: '1:631469996703:ios:09bd6341f243e212fb00aa',
    messagingSenderId: '631469996703',
    projectId: 'test-fluternotify',
    storageBucket: 'test-fluternotify.appspot.com',
    iosClientId: '631469996703-n7lc32s1e3a2sn5i5bblqd329ic5v82n.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationsTeste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq-rkqEUoF-H9APgpqbfhoZoi5EpcydIk',
    appId: '1:631469996703:ios:09bd6341f243e212fb00aa',
    messagingSenderId: '631469996703',
    projectId: 'test-fluternotify',
    storageBucket: 'test-fluternotify.appspot.com',
    iosClientId: '631469996703-n7lc32s1e3a2sn5i5bblqd329ic5v82n.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationsTeste',
  );
}
